export const EVENTS = {
  BOOKING_REQUESTED: "BOOKING_REQUESTED",
  PRICE_CALCULATED: "PRICE_CALCULATED",
  DISCOUNT_CHECKED: "DISCOUNT_CHECKED",
  PAYMENT_STARTED: "PAYMENT_STARTED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED"
};
